### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest

### ISSUE THREAD

**Issue by tutucoming** [seal-hub/ERCatcher#2]
Hi Sir,
I build ERCatcher by  `./gradlew clean jar`,and build successful.
Then i try to './run-dataset.sh dataset_name',but the program did not execute successfully，the following is the code generated by the running `./run-dataset.sh Curated`
`Analyzing Aard ...
Starting WholeProcess...
        Starting FlowDroid Setup...
Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest
        at com.ercatcher.Util.processManifest(Util.java:34)
        at com.ercatcher.Main.eventRaceSetupSoot(Main.java:253)
        at com.ercatcher.Main.doAnalysis(Main.java:63)
        at com.ercatcher.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.android.manifest.ProcessManifest
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Analyzing Browser ...
Starting WholeProcess...
        Starting FlowDroid Setup...
Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest
        at com.ercatcher.Util.processManifest(Util.java:34)
        at com.ercatcher.Main.eventRaceSetupSoot(Main.java:253)
        at com.ercatcher.Main.doAnalysis(Main.java:63)
        at com.ercatcher.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.android.manifest.ProcessManifest
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Analyzing CleanMaster ...
Starting WholeProcess...
        Starting FlowDroid Setup...
Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest
        at com.ercatcher.Util.processManifest(Util.java:34)
        at com.ercatcher.Main.eventRaceSetupSoot(Main.java:253)
        at com.ercatcher.Main.doAnalysis(Main.java:63)
        at com.ercatcher.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.android.manifest.ProcessManifest
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Analyzing ClipStack ...
Starting WholeProcess...
        Starting FlowDroid Setup...
Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest
        at com.ercatcher.Util.processManifest(Util.java:34)
        at com.ercatcher.Main.eventRaceSetupSoot(Main.java:253)
        at com.ercatcher.Main.doAnalysis(Main.java:63)
        at com.ercatcher.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.android.manifest.ProcessManifest
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Analyzing ConnectBot ...
Starting WholeProcess...
        Starting FlowDroid Setup...
Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest
        at com.ercatcher.Util.processManifest(Util.java:34)
        at com.ercatcher.Main.eventRaceSetupSoot(Main.java:253)
        at com.ercatcher.Main.doAnalysis(Main.java:63)
        at com.ercatcher.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.android.manifest.ProcessManifest
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Analyzing DashClock ...
Starting WholeProcess...
        Starting FlowDroid Setup...
Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest
        at com.ercatcher.Util.processManifest(Util.java:34)
        at com.ercatcher.Main.eventRaceSetupSoot(Main.java:253)
        at com.ercatcher.Main.doAnalysis(Main.java:63)
        at com.ercatcher.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.android.manifest.ProcessManifest
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Analyzing Dns66 ...
Starting WholeProcess...
        Starting FlowDroid Setup...
Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest
        at com.ercatcher.Util.processManifest(Util.java:34)
        at com.ercatcher.Main.eventRaceSetupSoot(Main.java:253)
        at com.ercatcher.Main.doAnalysis(Main.java:63)
        at com.ercatcher.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.android.manifest.ProcessManifest
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Analyzing FBReader ...
Starting WholeProcess...
        Starting FlowDroid Setup...
Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest
        at com.ercatcher.Util.processManifest(Util.java:34)
        at com.ercatcher.Main.eventRaceSetupSoot(Main.java:253)
        at com.ercatcher.Main.doAnalysis(Main.java:63)
        at com.ercatcher.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.android.manifest.ProcessManifest
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Analyzing Firefox ...
Starting WholeProcess...
        Starting FlowDroid Setup...
Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest
        at com.ercatcher.Util.processManifest(Util.java:34)
        at com.ercatcher.Main.eventRaceSetupSoot(Main.java:253)
        at com.ercatcher.Main.doAnalysis(Main.java:63)
        at com.ercatcher.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.android.manifest.ProcessManifest
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Analyzing InstaMaterial ...
Starting WholeProcess...
        Starting FlowDroid Setup...
Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest
        at com.ercatcher.Util.processManifest(Util.java:34)
        at com.ercatcher.Main.eventRaceSetupSoot(Main.java:253)
        at com.ercatcher.Main.doAnalysis(Main.java:63)
        at com.ercatcher.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.android.manifest.ProcessManifest
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Analyzing K9Mail ...
Starting WholeProcess...
        Starting FlowDroid Setup...
Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest
        at com.ercatcher.Util.processManifest(Util.java:34)
        at com.ercatcher.Main.eventRaceSetupSoot(Main.java:253)
        at com.ercatcher.Main.doAnalysis(Main.java:63)
        at com.ercatcher.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.android.manifest.ProcessManifest
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Analyzing KissLauncher ...
Starting WholeProcess...
        Starting FlowDroid Setup...
Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest
        at com.ercatcher.Util.processManifest(Util.java:34)
        at com.ercatcher.Main.eventRaceSetupSoot(Main.java:253)
        at com.ercatcher.Main.doAnalysis(Main.java:63)
        at com.ercatcher.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.android.manifest.ProcessManifest
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Analyzing MiMangaNu ...
Starting WholeProcess...
        Starting FlowDroid Setup...
Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest
        at com.ercatcher.Util.processManifest(Util.java:34)
        at com.ercatcher.Main.eventRaceSetupSoot(Main.java:253)
        at com.ercatcher.Main.doAnalysis(Main.java:63)
        at com.ercatcher.Main.main(Main.java:54)
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.android.manifest.ProcessManifest
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
`
Class `java.lang.NoClassDefFoundError: soot/jimple/infoflow/android/manifest/ProcessManifest` has already include in the package import by`implementation group: 'de.tud.sse', name: 'soot-infoflow-android', version: '2.7.1'`，could you please tell me what caused this。

**Comment by tutucoming** [comment]
Using Gradle imports can `soot-infoflow-android` cause the above problems. 
The solution is to download the JAR packages to your local lib folder and add the local libraries to your IDE.

The jar package can be downloaded by the link below：
`soot-infoflow-android`
https://mvnrepository.com/artifact/de.tud.sse/soot-infoflow-android/2.7.1 
`soot-infoflow`
[https://mvnrepository.com/artifact/de.tud.sse/soot-infoflow](url)
